# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 592137afe113266d7e7fbb269e69223af11634ff360f9a4296600da236b2ff6cb1fa93ca7e5e457c707c2aa335b6b4bdb43a9f799777afc0859f5f83b9f67ebd

test:
  secret_key_base: da6eea093d376b230d0e1c44b991ce311ff8d4e758587115b5f48fe88e46e7d172f41996ff8ee2f1f8fdb74154c177caf0b6a63b0e8048336679b78b412b80f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
